default: 
	cd modules; $(MAKE); 
	cd dmft; $(MAKE); 
	cd qmc; $(MAKE); 
	cd maxent; $(MAKE); 
	
clean: 
	cd modules; $(MAKE) clean; 
	cd dmft; $(MAKE) clean;
	cd qmc; $(MAKE) clean;
	cd maxent; $(MAKE) clean; 
	
